# Global log level ：panic、fatal、error、warn、info、debug
LOG_LEVEL = "debug"

# MySQL conf
ADDR = "IP:Port"
USER = "user name"
PASSWORD = "password"
# 包含的数据库和表，正则匹配
INCLUDE_TABLE_REGEX = ["db name\\.table name$", "db name\\.table name"]
# 忽略的数据库和表
EXCLUDE_TABLE_REGEX = []

[CONFIG.DUMP]
mysqldump = "mysqldump"
DISCARD_ERR = true
SKIP_MASTER_DATA = true
